packages:
  - "."
  - "examples/*"
onlyBuiltDependencies:
  - embedded-postgres
  - "@embedded-postgres/linux-x64"
  - "@embedded-postgres/linux-arm64"
  - "@embedded-postgres/darwin-x64"
  - "@embedded-postgres/darwin-arm64"
