import { rmSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { excludeFromGit } from './git-exclude.js';

/**
 * `isolate`: one app and database per worker (env module, no webServer, workers and baseURL set).
 * `passthrough`: the repo's config unchanged (webServer, workers, env), plus the isolate reporter.
 */
export type WrapperMode = 'isolate' | 'passthrough';

/** What the generated wrapper needs to know. */
export interface WrapperOptions {
  mode: WrapperMode;
  /** Absolute path of the repo's Playwright config. */
  repoConfig: string;
  /** Where the isolate reporter writes its results unless ISOLATE_RESULTS_FILE overrides it. */
  outputFile: string;
  /** Directory test ids and file paths are relative to. */
  rootDir: string;
  /** Reporters named by a `--reporter` flag moved out of the command, or null to keep the config's. */
  cliReporters: string[] | null;
}

/** The generated files of one run. */
export interface Wrapper {
  configFile: string;
  /** Every file this wrapper may have written. */
  files: string[];
  remove(): void;
}

/** Name of the generated config, written next to the repo's Playwright config. */
export const WRAPPER_CONFIG = '.isolate.playwright.config.ts';

/** Name of the generated env module the wrapper config imports first in isolate mode. */
export const ENV_MODULE = '.isolate.env.ts';

const REPORTER = fileURLToPath(new URL('./reporter.js', import.meta.url));

const HEADER = '// Generated by isolate for one run and removed when the run ends. Do not edit.\n';

const ENV_MODULE_SOURCE = `${HEADER}// Runs in Playwright's main process (worker 0's values) and again in every worker before the repo's config loads.
const envs: Record<string, string>[] = JSON.parse(process.env.ISOLATE_WORKER_ENVS ?? '[]');
const index = Number(process.env.TEST_PARALLEL_INDEX ?? '0');
if (index >= envs.length) {
  throw new Error(
    \`isolate started \${envs.length} app(s), but Playwright is running more workers (worker \${index}). Remove --workers from the command so Playwright runs one worker per app.\`,
  );
}
Object.assign(process.env, envs[index]);
`;

/** The import specifier of the repo's config from the wrapper: extensionless for .ts, explicit otherwise. */
function importSpecifier(repoConfig: string): string {
  const base = path.basename(repoConfig);
  return `./${base.endsWith('.ts') ? base.slice(0, -'.ts'.length) : base}`;
}

/** Source of the expression that lists the repo's reporters in array form. */
function repoReportersSource(cliReporters: string[] | null): string {
  if (cliReporters !== null) return JSON.stringify(cliReporters.map((name) => [name]));
  return "base.reporter === undefined ? [[process.env.CI ? 'dot' : 'list']] : typeof base.reporter === 'string' ? [[base.reporter]] : base.reporter";
}

/** Source of the wrapper config for one mode. */
function wrapperSource(options: WrapperOptions): string {
  const reporterOptions = `{ outputFile: process.env.ISOLATE_RESULTS_FILE ?? ${JSON.stringify(options.outputFile)}, rootDir: ${JSON.stringify(options.rootDir)} }`;
  const reporter = `[...(${repoReportersSource(options.cliReporters)}), [${JSON.stringify(REPORTER)}, ${reporterOptions}]]`;
  const importBase = `import base from ${JSON.stringify(importSpecifier(options.repoConfig))};\n`;
  if (options.mode === 'passthrough') {
    return `${HEADER}${importBase}\nexport default { ...base, reporter: ${reporter} };\n`;
  }
  return `${HEADER}import './${ENV_MODULE.slice(0, -'.ts'.length)}';
${importBase}
const tagRequests = process.env.ISOLATE_TAG_REQUESTS === '1';

function withIsolate(use: any, inherited?: any): any {
  const isolated = { ...use, baseURL: process.env.ISOLATE_BASE_URL };
  if (!tagRequests) return isolated;
  const worker = process.env.ISOLATE_APP_INDEX ?? '0';
  return { ...isolated, extraHTTPHeaders: { ...inherited?.extraHTTPHeaders, ...use?.extraHTTPHeaders, 'x-isolate-worker': worker } };
}

export default {
  ...base,
  webServer: undefined,
  workers: Number(process.env.ISOLATE_WORKERS),
  use: withIsolate(base.use),
  ...(base.projects ? { projects: base.projects.map((project: any) => ({ ...project, use: withIsolate(project.use, base.use) })) } : {}),
  reporter: ${reporter},
};
`;
}

/** Writes the wrapper config (and in isolate mode the env module) next to the repo's Playwright config. */
export function writeWrapper(options: WrapperOptions): Wrapper {
  const dir = path.dirname(options.repoConfig);
  const configFile = path.join(dir, WRAPPER_CONFIG);
  const envFile = path.join(dir, ENV_MODULE);
  excludeFromGit(dir, [ENV_MODULE, WRAPPER_CONFIG]);
  if (options.mode === 'isolate') writeFileSync(envFile, ENV_MODULE_SOURCE);
  writeFileSync(configFile, wrapperSource(options));
  const files = [envFile, configFile];
  return {
    configFile,
    files,
    remove: () => {
      for (const file of files) rmSync(file, { force: true });
    },
  };
}
