/**
 * Loaded with `NODE_OPTIONS=--require` into every Node process of a traced app (only by `isolate trace`). It starts
 * V8 precise coverage in-process before any app code runs, counts in-flight HTTP requests, and answers "take" requests
 * on $ISOLATE_TRACE_DIR/w<worker>/<pid>.sock with the functions executed in repo files since the previous take. It
 * never writes to stdout; if anything fails it prints one line to stderr and stays inert.
 */
import { mkdirSync, rmSync } from 'node:fs';
import http from 'node:http';
import https from 'node:https';
import type { Profiler } from 'node:inspector';
import { Session } from 'node:inspector/promises';
import net from 'node:net';
import path from 'node:path';
import { setTimeout as delay } from 'node:timers/promises';
import { fileURLToPath } from 'node:url';
import { isMainThread } from 'node:worker_threads';
import type { ServerScript, TakeReply } from './protocol.js';

/** Longest wait for in-flight HTTP requests to finish before a take proceeds anyway. */
const DRAIN_TIMEOUT_MS = 2000;
const DRAIN_POLL_MS = 10;

/** Module URLs generated by bundlers; kept as they are, the CLI decides how to map them. */
const BUNDLER_SCHEMES = ['webpack-internal:', 'webpack:'];

/** The one request a socket client can send. */
const TAKE_REQUEST = 'take';

let inFlight = 0;

function warn(message: string): void {
  process.stderr.write(`[isolate trace] pid ${process.pid}: ${message}\n`);
}

function describe(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

/** Counts a request as in flight until its response finishes or its connection closes, whichever comes first. */
function trackResponse(response: http.ServerResponse): void {
  inFlight++;
  let done = false;
  const finish = () => {
    if (done) return;
    done = true;
    inFlight--;
  };
  response.once('finish', finish);
  response.once('close', finish);
}

interface Emitter {
  emit(event: string | symbol, ...args: unknown[]): boolean;
}

/** Wraps a server class's `emit` so that every 'request' event is tracked. */
function countRequests(prototype: Emitter): void {
  const original = prototype.emit;
  prototype.emit = function (this: Emitter, event: string | symbol, ...args: unknown[]): boolean {
    if (event === 'request' && args[1] instanceof http.ServerResponse) trackResponse(args[1]);
    return original.call(this, event, ...args);
  };
}

/** Resolves true once no request is in flight, or false if some still are after DRAIN_TIMEOUT_MS. */
async function drained(): Promise<boolean> {
  const deadline = Date.now() + DRAIN_TIMEOUT_MS;
  while (inFlight > 0) {
    if (Date.now() >= deadline) return false;
    await delay(DRAIN_POLL_MS);
  }
  return true;
}

/** True for scripts the CLI can map to repo files: file:// URLs under the root, or bundler URLs; never node_modules. */
function isRepoScript(url: string, root: string): boolean {
  if (url.includes('/node_modules/')) return false;
  if (BUNDLER_SCHEMES.some((scheme) => url.startsWith(scheme))) return true;
  if (!url.startsWith('file:')) return false;
  try {
    return fileURLToPath(url).startsWith(root + path.sep);
  } catch {
    return false;
  }
}

/** The functions of one script that ran since the previous take. */
function executed(script: Profiler.ScriptCoverage): ServerScript {
  const functions = script.functions.flatMap((fn) => {
    const range = fn.ranges[0];
    if (range === undefined || range.count === 0) return [];
    const { startOffset, endOffset, count } = range;
    return [{ name: fn.functionName, startOffset, endOffset, count, isTopLevel: startOffset === 0 && fn.functionName === '' }];
  });
  return { url: script.url, functions };
}

/** Waits for in-flight requests, then takes (and thereby resets) the precise coverage counts. */
async function take(session: Session, root: string): Promise<TakeReply> {
  const timedOut = !(await drained());
  const { result } = await session.post('Profiler.takePreciseCoverage');
  const scripts = result
    .filter((script) => isRepoScript(script.url, root))
    .map(executed)
    .filter((script) => script.functions.length > 0);
  return { pid: process.pid, timedOut, scripts };
}

/** Answers one socket client: reads a line, and replies to "take" with the coverage as JSON. */
function serve(socket: net.Socket, session: Session, root: string): void {
  let received = '';
  socket.on('error', () => {}); // A client that goes away must not crash the app.
  socket.on('data', (chunk) => {
    received += chunk.toString();
    if (!received.includes('\n')) return;
    socket.removeAllListeners('data');
    const reply = received.trim() === TAKE_REQUEST ? take(session, root) : Promise.reject(new Error(`unknown request ${received.trim()}`));
    reply.then(
      (value) => socket.end(JSON.stringify(value)),
      (error: unknown) => socket.end(JSON.stringify({ error: describe(error) })),
    );
  });
}

/** Listens on <traceDir>/w<worker>/<pid>.sock without keeping the process alive, and removes the socket file on exit. */
function listen(traceDir: string, session: Session, root: string): void {
  const dir = path.join(traceDir, `w${process.env.ISOLATE_WORKER_INDEX ?? '0'}`);
  mkdirSync(dir, { recursive: true });
  const socketPath = path.join(dir, `${process.pid}.sock`);
  rmSync(socketPath, { force: true });
  const server = net.createServer((socket) => serve(socket, session, root));
  server.on('error', (error) => {
    session.disconnect();
    warn(`not tracing this process: trace socket ${socketPath} failed: ${error.message}`);
  });
  server.listen(socketPath);
  server.unref();
  process.once('exit', () => {
    try {
      rmSync(socketPath, { force: true });
    } catch {
      // Nothing useful can be done while the process exits.
    }
  });
}

/** Starts coverage synchronously (the inspector dispatches in-process), then counts requests and opens the socket. */
function start(traceDir: string): void {
  const root = process.env.ISOLATE_TRACE_ROOT;
  if (root === undefined || root === '') throw new Error('ISOLATE_TRACE_ROOT is not set');
  const session = new Session();
  session.connect();
  const started = Promise.all([session.post('Profiler.enable'), session.post('Profiler.startPreciseCoverage', { callCount: true, detailed: false })]);
  countRequests(http.Server.prototype as unknown as Emitter);
  countRequests(https.Server.prototype as unknown as Emitter);
  started
    .then(() => listen(traceDir, session, root))
    .catch((error: unknown) => {
      session.disconnect();
      warn(`not tracing this process: ${describe(error)}`);
    });
}

const traceDir = process.env.ISOLATE_TRACE_DIR;
if (traceDir !== undefined && traceDir !== '' && isMainThread) {
  try {
    start(traceDir);
  } catch (error) {
    warn(`not tracing this process: ${describe(error)}`);
  }
}
